name: Build, Scan, Push
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
      aws-role-to-assume:
        required: true
        type: string
    secrets:
      aws-account-id:
        required: true
      docker-user:
        required: true
      docker-pat:
        required: true
    outputs:
      image_tag:
        description: "The unique tag of the built image"
        value: ${{ jobs.build-push.outputs.image_tag }}

permissions:
  id-token: write
  contents: read

jobs:
  job-build-scan-push:
    name: Build, Scan & Push to ECR
    runs-on: ubuntu-24.04
    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.tag }}
      
    steps:
      - name: Check out code
        uses: actions/checkout@<COMMIT_SHA>

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@<COMMIT_SHA>

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@<COMMIT_SHA>
        with:
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          aws-region: ${{ inputs.aws-region }}

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@<COMMIT_SHA>

      - name: Log in to Docker Hub (for Scout)
        uses: docker/login-action@<COMMIT_SHA>
        with:
          username: ${{ secrets.docker-user }}
          password: ${{ secrets.docker-pat }}

      - name: Define the unique image tag
        id: set-image-tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Scan Image
        id: build-scan
        run: |
          docker build \
            --target production \
            -t ${{ secrets.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:${{ steps.set-image-tag.outputs.tag }} \
            .
            
          docker scout cves \
            --exit-code \
            --only-severities CRITICAL,HIGH \
            ${{ secrets.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:${{ steps.set-image-tag.outputs.tag }}
            
      - name: Push image to ECR
        run: |
          docker push ${{ secrets.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}:${{ steps.set-image-tag.outputs.tag }}
