name: Main

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  main-check-security-quality:
    name: Security and Code Quality Checks
    uses: ./.github/workflows/check-security-quality.yml

  main-deploy-docs:
    name: Deploy Documentation
    needs: main-check-security-quality
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    uses: ./.github/workflows/deploy-docs.yml
    secrets: inherit

  # main-build-scan-push:
  #   name: Build, Scan & Push to ECR
  #   needs: security-quality-checks
    
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
  #   uses: ./.github/workflows/build-scan-push.yml
  #   with:
  #     aws-region: ${{ env.AWS_REGION }}
  #     ecr-repository: ${{ env.ECR_REPOSITORY }}
  #     aws-role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
  #   secrets:
  #     aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
  #     docker-user: ${{ secrets.DOKCER_USER }}
  #     docker-pat: ${{ secrets.DOCKER_PAT }}

  # main-deploy-fargate:
  #   name: Deploy to Fargate
  #   needs: build-scan-push
    
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
  #   uses: ./.github/workflows/deploy-fargate.yml
  #   with:
  #     aws-region: ${{ env.AWS_REGION }}
  #     ecs-cluster: ${{ env.ECS_CLUSTER }}
  #     ecs-service: ${{ env.ECS_SERVICE }}
  #     ecs-task-definition: ${{ env.ECS_TASK_DEFINITION }}
  #     container-name: ${{ env.CONTAINER_NAME }}
  #     aws-role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
  #     image-tag: ${{ needs.build-scan-and-push.outputs.image_tag }}
  #     ecr-repository: ${{ env.ECR_REPOSITORY }}
  #   secrets:
  #     aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
