name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read 

jobs:
  check-security-quality:
    name: Check security & quality
    uses: ./.github/workflows/check-security-quality.yml

  deploy-docs:
    name: Deploy documentations
    needs: check-security-quality
    
    if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'development')

    permissions:
      contents: write 
      
    uses: ./.github/workflows/deploy-docs.yml
    secrets:
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      POSTMAN_COLLECTION_ID_MAIN_V1: ${{ secrets.POSTMAN_COLLECTION_ID_MAIN_V1 }}
      POSTMAN_COLLECTION_ID_MAIN_V2: ${{ secrets.POSTMAN_COLLECTION_ID_MAIN_V2 }}
      POSTMAN_COLLECTION_ID_DEV_V1: ${{ secrets.POSTMAN_COLLECTION_ID_DEV_V1 }}
      POSTMAN_COLLECTION_ID_DEV_V2: ${{ secrets.POSTMAN_COLLECTION_ID_DEV_V2 }}

  # build-scan-push:
  #   name: Build, Scan & Push to ECR
  #   needs: check-security-quality
    
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
  #   uses: ./.github/workflows/build-scan-push.yml
  #   with:
  #     aws-region: ${{ env.AWS_REGION }}
  #     ecr-repository: ${{ env.ECR_REPOSITORY }}
  #     aws-role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
  #   secrets:
  #     aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
  #     docker-user: ${{ secrets.DOKCER_USER }}
  #     docker-pat: ${{ secrets.DOCKER_PAT }}

  # deploy-fargate:
  #   name: Deploy to Fargate
  #   needs: build-scan-push
    
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
  #   uses: ./.github/workflows/deploy-fargate.yml
  #   with:
  #     aws-region: ${{ env.AWS_REGION }}
  #     ecs-cluster: ${{ env.ECS_CLUSTER }}
  #     ecs-service: ${{ env.ECS_SERVICE }}
  #     ecs-task-definition: ${{ env.ECS_TASK_DEFINITION }}
  #     container-name: ${{ env.CONTAINER_NAME }}
  #     aws-role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
  #     image-tag: ${{ needs.build-scan-and-push.outputs.image_tag }}
  #     ecr-repository: ${{ env.ECR_REPOSITORY }}
  #   secrets:
  #     aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
