name: Validate security & quality
on:
  workflow_call:

jobs:
  security-quality:
    name: Security and code quality
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5

      - name: Check for Shadow APIs
        run: |
          if grep -rE --exclude-dir=node_modules --exclude-dir=dist "(@ApiExcludeEndpoint\(true\)|@Controller\('_dev'\))" .; then
            echo "::error::Shadow API patterns found! Remove '@ApiExcludeEndpoint' or '_dev' controller usages."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2
        with:
          cache: 'npm'
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Check for vulnerabilities
        run: npx audit-ci --high

      - name: Lint code
        run: npm run lint

  unit-tests:
    name: Unit tests & coverage
    needs: security-quality
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5

      - name: Setup Node.js
        uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2
        with:
          cache: 'npm'
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:cov

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 1

  static-contract-e2e-tests:
    name: Static contract & E2E tests
    needs: security-quality
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5

      - name: Setup Node.js
        uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2
        with:
          cache: 'npm'
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build:ci

      - name: Lint Swagger contract
        run: npm run lint:contract

      - name: Run end-to-end tests
        run: npm run test:e2e

  dynamic-contract-tests:
    name: Dynamic contract tests
    needs: security-quality
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5

      - name: Setup Node.js
        uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2
        with:
          cache: 'npm'
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Build app & generate Swagger files
        run: npm run build:ci

      - name: Start server and wait
        run: |
          node dist/src/main &
          npx wait-on http://localhost:3000/v1/healthcheck -t 30000

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.13'

      - name: Install Schemathesis
        run: pip install schemathesis

      - name: Run dynamic contract tests
        run: |
          schemathesis run dist/swagger-v1.json --url http://localhost:3000 --checks all --exclude-checks unsupported_method,positive_data_acceptance
          schemathesis run dist/swagger-v2.json --url http://localhost:3000 --checks all --exclude-checks unsupported_method,positive_data_acceptance

      - name: Rename swagger specs
        if: github.ref_name == 'main' || github.ref_name == 'development'
        run: |
          SAFE_BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          cp dist/swagger-v1.json dist/swagger-${SAFE_BRANCH_NAME}-v1.json
          cp dist/swagger-v2.json dist/swagger-${SAFE_BRANCH_NAME}-v2.json

      - name: Upload swagger artifacts
        if: github.ref_name == 'main' || github.ref_name == 'development'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: openapi-specs
          path: dist/swagger-*-v*.json
          retention-days: 1