name: Deployment

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  call-job-security-code-quality-checks:
    name: Security and Code Quality Checks
    uses: ./.github/workflows/job-security-code-quality-checks.yml

  # call-job-build-scan-push:
  #   name: Build, Scan & Push to ECR
  #   needs: call-job-security-code-quality-checks
    
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
  #   uses: ./.github/workflows/job-build-scan-push.yml
  #   with:
  #     aws-region: ${{ env.AWS_REGION }}
  #     ecr-repository: ${{ env.ECR_REPOSITORY }}
  #     aws-role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
  #   secrets:
  #     aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
  #     docker-user: ${{ secrets.DOKCER_USER }}
  #     docker-pat: ${{ secrets.DOCKER_PAT }}

  # call-job-deploy-fargate:
  #   name: Deploy to Fargate
  #   needs: call-job-build-scan-push
    
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
  #   uses: ./.github/workflows/job-deploy-fargate.yml
  #   with:
  #     aws-region: ${{ env.AWS_REGION }}
  #     ecs-cluster: ${{ env.ECS_CLUSTER }}
  #     ecs-service: ${{ env.ECS_SERVICE }}
  #     ecs-task-definition: ${{ env.ECS_TASK_DEFINITION }}
  #     container-name: ${{ env.CONTAINER_NAME }}
  #     aws-role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
  #     image-tag: ${{ needs.build-scan-and-push.outputs.image_tag }}
  #     ecr-repository: ${{ env.ECR_REPOSITORY }}
  #   secrets:
  #     aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
